# Generated by Django 5.2.14 on 2026-05-16 19:45

import django.db.models.deletion
import inbox.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InboxHandle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('handle', models.SlugField(help_text='The local part of the email-to-inbox address', max_length=60, unique=True)),
                ('secret_token', models.CharField(default=inbox.models._gen_token, help_text='Required as a +tag suffix to prevent spam', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_handle', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inbox_handle',
            },
        ),
        migrations.CreateModel(
            name='InboxMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_from', models.CharField(max_length=320)),
                ('subject', models.CharField(blank=True, max_length=512)),
                ('body_text', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('disposition', models.CharField(choices=[('created', 'Created an action'), ('rejected_auth', 'Rejected: bad token'), ('rejected_quota', 'Rejected: over quota'), ('error', 'Error during processing')], max_length=24)),
                ('error_message', models.TextField(blank=True)),
                ('action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tasks.action')),
                ('handle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='inbox.inboxhandle')),
            ],
            options={
                'db_table': 'inbox_message',
                'ordering': ['-received_at'],
            },
        ),
    ]
