# Generated by Django 5.2.14 on 2026-05-16 19:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Altitude',
            fields=[
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=2000)),
                ('is_collapsed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='altitudes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tasks_altitude',
            },
        ),
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tasks.context')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contexts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tasks_context',
                'ordering': ['position', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=256)),
                ('notes', models.TextField(blank=True, help_text='Markdown')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('is_collapsed', models.BooleanField(default=False, help_text='UI state in list view')),
                ('position', models.PositiveIntegerField(default=0)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tasks_project',
                'ordering': ['position', '-created'],
            },
        ),
        migrations.CreateModel(
            name='SavedView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('feed_slug', models.SlugField(blank=True, help_text='Public RSS/iCal feed slug', null=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('rule', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tasks_saved_view',
                'ordering': ['position', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SomedayList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('position', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='someday_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tasks_someday_list',
                'ordering': ['position', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=256)),
                ('notes', models.TextField(blank=True, help_text='Markdown')),
                ('status', models.CharField(choices=[('inbox', 'Inbox'), ('next', 'Next action'), ('scheduled', 'Scheduled'), ('waiting', 'Waiting on'), ('someday', 'Someday/maybe'), ('tickler', 'Tickler'), ('completed', 'Completed')], db_index=True, default='inbox', max_length=16)),
                ('starred', models.BooleanField(db_index=True, default=False)),
                ('effort', models.IntegerField(blank=True, choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], null=True)),
                ('minutes_required', models.PositiveIntegerField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, db_index=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_reminded_at', models.DateTimeField(blank=True, null=True)),
                ('position', models.IntegerField(default=0, help_text='Manual reorder within current view')),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to=settings.AUTH_USER_MODEL)),
                ('context', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='tasks.context')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='tasks.project')),
                ('someday_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='tasks.somedaylist')),
            ],
            options={
                'db_table': 'tasks_action',
                'ordering': ['position', '-created'],
                'indexes': [models.Index(fields=['user', 'deleted_at', 'completed_at', 'status'], name='i_user_del_comp_status'), models.Index(fields=['user', 'due_date'], name='i_user_due')],
            },
        ),
    ]
