# Generated by Django 5.2.14 on 2026-05-16 19:45

import accounts.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('handle', models.CharField(blank=True, help_text='Optional public handle; legacy username field', max_length=30, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=60)),
                ('last_name', models.CharField(blank=True, max_length=60)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'accounts_user',
            },
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hide_empty_contexts', models.BooleanField(default=False)),
                ('hide_empty_saved_views', models.BooleanField(default=False)),
                ('saved_views_enabled', models.BooleanField(default=True)),
                ('count_badges_on_contexts', models.BooleanField(default=True)),
                ('count_badges_on_projects', models.BooleanField(default=True)),
                ('use_stars', models.BooleanField(default=True)),
                ('default_landing_page', models.CharField(default='inbox', help_text='View slug to land on after login', max_length=40)),
                ('tz_name', models.CharField(default='UTC', help_text='IANA TZ string, e.g. America/Chicago', max_length=64)),
                ('reminder_email', models.EmailField(blank=True, help_text='Override; falls back to user.email', max_length=254)),
                ('reminder_time', models.TimeField(default='08:00')),
                ('reminder_tickler_behavior', models.IntegerField(choices=[(0, 'Omit from digest'), (1, "Include today's ticklers only"), (2, "Include today's + overdue"), (3, 'Include all open ticklers')], default=2)),
                ('reminder_action_behavior', models.IntegerField(choices=[(0, 'Omit from digest'), (1, 'Starred only'), (2, 'All next actions')], default=1)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'preferences',
                'verbose_name_plural': 'preferences',
                'db_table': 'accounts_preferences',
            },
        ),
    ]
